config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  resources :articles

  get 'analytics', to: 'search_logs#analytics'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  searchkick text_middle: %i[title body author]

  after_save :reindex_article

  validates :title, :author, :body, presence: true
  validates :title, length: { minimum: 6 }

  private

  def reindex_article
    Article.reindex
  end
end

app/models/search_log.rb
# frozen_string_literal: true

class SearchLog < ApplicationRecord
  validates :search_query, :ip_address, :timestamp, presence: true
  validates :search_query, length: { maximum: 255 }
  validates :ip_address, format: { with: /\A(?:[0-9]{1,3}\.){3}[0-9]{1,3}\z/,
                                   message: 'should be a valid IP address' }
  validates :timestamp, timeliness: { type: :datetime }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :author)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @results = search_for_articles
    log_search(params[:query]) unless params[:query].blank?
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('articles', partial: 'articles/articles',
                                                             locals: { articles: @results })
      end
    end
  end

  def suggestions
    @results = search_for_articles
    log_search(params[:query]) unless params[:query].blank?
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('suggestions', partial: 'search/suggestions',
                                                                locals: { results: @results })
      end
    end
  end

  private

  def search_for_articles
    params[:query].blank? ? Article.all : search_articles_by_query
  end

  def search_articles_by_query
    Article.search(params[:query], fields: %i[title body author], operator: 'or', match: :text_middle)
  end

  def log_search(query)
    existing_query = fetch_existing_query

    if query.present?
      update_or_create_query(query, existing_query)
    else
      delete_query(existing_query)
    end
  end

  def fetch_existing_query
    SearchLog.where(ip_address: request.remote_ip).last
  end

  def update_or_create_query(query, existing_query)
    if existing_query && query.include?(existing_query.search_query)
      existing_query.update(search_query: query)
    else
      create_search_log(query)
    end
  end

  def create_search_log(query)
    SearchLog.create(
      search_query: query,
      ip_address: request.remote_ip,
      timestamp: Time.now
    )
  end

  def delete_query(existing_query)
    existing_query&.destroy
  end
end

app/controllers/search_logs_controller.rb
# frozen_string_literal: true

class SearchLogsController < ApplicationController
  def analytics
    all_queries = SearchLog.where.not(search_query: nil).pluck(:search_query)

    final_search_queries = []

    all_queries.each do |query|
      is_subset = false
      all_queries.each do |other_query|
        next if query == other_query

        if other_query.include?(query)
          is_subset = true
          break
        end
      end

      final_search_queries << query unless is_subset
    end

    @search_logs = final_search_queries.group_by { |query| query }.transform_values(&:count)
                                       .sort_by { |_key, value| value }.reverse.to_h.first(10)

    render 'analytics'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= article.author %>
  </p>

</div>

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
<div class="p-4 border border-gray-300 rounded-lg my-2 shadow">
  <h2 class="text-2xl font-bold text-purple-700"><%= article.title %></h2>
  <p class="text-gray-700"><%= article.body %></p>
  <p class="text-gray-700">written by <%= article.author %></p>

  <p><%= link_to "Show this article", article, class: "text-blue-400" %></p>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl text-center mt-4 mb-3" >Articles</h1>

<div class="flex justify-center">
  <%= render partial: "search/form", locals: { results: [] } %>
</div>

<%= link_to "Analytics", analytics_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

<div id="articles" class="mt-4 mx-10">
  <%= render "articles/articles", articles: @articles %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<!-- show.html.erb -->

<div class="container mx-auto p-8">
  <p class="text-2xl font-bold text-blue-700 mb-4"><%= notice %></p>

  <div class="border-2 border-gray-300 p-6 rounded-md shadow-lg mb-8">
    <%= render @article %>
  </div>

  <div class="flex justify-between items-center">
    <%= link_to "Edit this article", edit_article_path(@article), class: "py-2 px-4 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 hover:text-gray-100 mr-4" %>
    <%= link_to "Back to articles", articles_path, class: "py-2 px-4 bg-gray-500 text-white font-semibold rounded hover:bg-gray-600 hover:text-gray-100 mr-4" %>
    <%= button_to "Destroy this article", @article, method: :delete, data: { confirm: "Are you sure?" }, class: "py-2 px-4 bg-red-500 text-white font-semibold rounded hover:bg-red-600 hover:text-gray-100" %>
  </div>
</div>



<!-- <p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div> -->

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Realtimesearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    

    <%= stylesheet_link_tag "application", "data-turbo-track":
    "reload" %> <%= javascript_include_tag "application", "data-turbo-track":
    "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :post, class: "w-60", data: {
  controller: "search",
  action: "keyup->search#suggestions",
  suggestions_url: search_suggestions_path,

}) do |form| %>

<div class="relative">
  <%= form.text_field :query, data: {
    search_target: "input",
    action: "blur->search#hideSuggestions",
  },
  class: "w-full border border-gray-300 rounded-lg px-3 py-2 pr-10 placeholder-gray-500 text-sm focus:outline-none focus:ring-1 focus:ring-purple-500 focus:border-purple-500", 
  placeholder: "Search articles...", autocomplete: "off" %>
  
  <div class="absolute inset-y-0 right-0 flex items-center">
    <button type="submit" class="bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded">
      Search
    </button>
  </div>

  <div id="suggestions" 
    class="absolute w-full mt-2 bg-white rounded-lg shadow-lg"
    data-search-target="suggestions" data-action="mousedown->search#childClicked">
    <%= render partial: "search/suggestions", locals: {results: results} %>
  </div>

</div>

<%end%>




<div class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
  <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 14h16" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 18h16" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 6h16" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M8 10h.01" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M8 14h.01" />
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M8 18h.01" />
  </svg>
</div>

app/views/search/_suggestions.html.erb
<% if results.any? %>
  <div class="absolute w-full overflow-y-auto max-h-60 bg-white rounded-lg shadow-lg">
    <% results.each do |result| %>
      <div class="px-4 py-2 hover:bg-gray-100 cursor-pointer suggestion-item" data-action="click->search#childClicked">
        <%= link_to result.title, result, class: "text-blue-500" %>
      </div>
    <% end %>
  </div>
<%end%>

app/views/search_logs/analytics.html.erb

<div class="mt-5 mx-2">
  <%= link_to "Back to Articles", articles_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2" %>

</div>

<% @search_logs.each do |search_query, count| %>
  <p><%= search_query %>: <%= count %></p>
<% end %>

<%= column_chart @search_logs, id: "searchTrendChart", height: "400px", colors: ["#36A2EB"] %>

<%= pie_chart @search_logs, id: "searchTrendChart", height: "400px", colors: ["#36A2EB"] %>